version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - ./cake2:/var/www/html
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - cakephp-network

  redis:
    image: redis:6-alpine
    ports:
      - "6379:6379"
    networks:
      - cakephp-network

networks:
  cakephp-network:
    driver: bridge
